name: ndp_inventory_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  barcode_widget: ^2.0.4
  http: ^1.5.0
  printing: ^5.14.3
  pdf: ^3.12.0
  shared_preferences: ^2.5.5
  fl_chart: ^0.69.0
  image_picker: ^1.2.2
  intl: ^0.19.0
  dropdown_search: ^6.0.2
  flutter_launcher_icons: ^0.14.4
  file_selector: ^1.1.0
  video_player: ^2.6.0
  video_player_win: ^3.2.0

 

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/images/app_icon.png"
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/ndp_logo.png